@startuml
left to right direction
usecase "Iniciar sesion" as is
usecase "Recuperar contraseña" as rc
usecase "Modificar contraseña" as mc
usecase "Cerrar sesión" as cs
usecase "Registrar usuario" as ru
usecase "Instalas programa" as ip
    Usuario -- is
    Usuario -- rc
    Usuario -- mc
    Usuario -- cs
    Administrador -- ru
    Administrador -- ip
    Usuario <|-- Administrador



@enduml