@startuml
left to right direction
actor "Cliente" as cl
usecase "Confirmar pedido" as cop
usecase "Cancelar pedido" as cap
usecase "Devolver cambio" as dc
    cl -- cop
    cl -- cap
    dc .. cop : <<include>>
    dc .. cap : <<include>>
@enduml