@startuml
left to right direction
actor "Cliente" as cl
actor "Restaurante" as res
rectangle {
    usecase "Mostrar menú" as mm
    usecase "Pedir comida" as pc
}
usecase "Entregar Comida" as ec
    cl -- mm
    cl -- pc
    res -- mm
    res -- ec

@enduml